### PR TITLE
Update Installation Url

### PR DESCRIPTION
**Pull request by mauriballes**

### CODE REVIEW

**Comment by raaaimund** [comment]
Thanks a lot for your PR @mauriballes! But the script from

`https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh`

is already in the script

`https://install.speedtest.net/app/cli/install.deb.sh`

included, or did I miss something here?

The `-y` argument I totally can understand. That's a good point.

**Comment by mauriballes** [comment]
No, you are right. I sent the PR because when I tried to build the image, for some reason the site was down. Then I noticed that the url was updated on Speedtest website, so I changed it and It worked!.
It's just and update, but you can close the PR if you want. 
BTW, thanks for the tool!

**Comment by raaaimund** [comment]
Thanks for your answer @mauriballes! Yes, I also thought that probably either something was blocked or down at the moment you tried to run. But good to know, because every time some resources can change/be down/be blocked.

**Comment by raaaimund** [comment]
**BUT** I just checked the install instructions on https://www.speedtest.net/apps/cli, and the URL you are using in the PR is also mentioned in the install instructions. So indeed, I think the better approach would be to use the URL you mentioned. I did not know that this URL also was used in the latest installation instructions.

Maybe they also changed it because hosting the script on some service like packagecloud.io results in much higher availability.

Thanks again for your PR @mauriballes!

**Pull request merged**
